package com.example.project_days.ui.theme

import androidx.compose.ui.graphics.Color

// Theme Light - Minimalista
val md_theme_light_primary = Color(0xFFE63946)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFE5E7)
val md_theme_light_onPrimaryContainer = Color(0xFF4A0006)
val md_theme_light_secondary = Color(0xFF8B5CF6)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF5F3FF)
val md_theme_light_onSecondaryContainer = Color(0xFF2E1065)
val md_theme_light_tertiary = Color(0xFF06B6D4)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE0F2FE)
val md_theme_light_onTertiaryContainer = Color(0xFF0C4A6E)
val md_theme_light_error = Color(0xFFDC2626)
val md_theme_light_errorContainer = Color(0xFFFEE2E2)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF7F1D1D)
val md_theme_light_background = Color(0xFFFAFAFA)
val md_theme_light_onBackground = Color(0xFF1F2937)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1F2937)
val md_theme_light_surfaceVariant = Color(0xFFF3F4F6)
val md_theme_light_onSurfaceVariant = Color(0xFF6B7280)
val md_theme_light_outline = Color(0xFFE5E7EB)
val md_theme_light_inverseOnSurface = Color(0xFFF9FAFB)
val md_theme_light_inverseSurface = Color(0xFF111827)
val md_theme_light_inversePrimary = Color(0xFFFF6B6B)
val md_theme_light_surfaceTint = Color(0xFFE63946)
val md_theme_light_outlineVariant = Color(0xFFF3F4F6)
val md_theme_light_scrim = Color(0xFF000000)

// Theme Dark - Minimalista
val md_theme_dark_primary = Color(0xFFFF6B6B)
val md_theme_dark_onPrimary = Color(0xFF5A0008)
val md_theme_dark_primaryContainer = Color(0xFF8B0012)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDADD)
val md_theme_dark_secondary = Color(0xFFA78BFA)
val md_theme_dark_onSecondary = Color(0xFF4C1D95)
val md_theme_dark_secondaryContainer = Color(0xFF6D28D9)
val md_theme_dark_onSecondaryContainer = Color(0xFFF5F3FF)
val md_theme_dark_tertiary = Color(0xFF22D3EE)
val md_theme_dark_onTertiary = Color(0xFF083344)
val md_theme_dark_tertiaryContainer = Color(0xFF0E7490)
val md_theme_dark_onTertiaryContainer = Color(0xFFE0F2FE)
val md_theme_dark_error = Color(0xFFFCA5A5)
val md_theme_dark_errorContainer = Color(0xFF991B1B)
val md_theme_dark_onError = Color(0xFF7F1D1D)
val md_theme_dark_onErrorContainer = Color(0xFFFEE2E2)
val md_theme_dark_background = Color(0xFF1B1C18)
val md_theme_dark_onBackground = Color(0xFFE4E3DB)
val md_theme_dark_surface = Color(0xFF1B1C18)
val md_theme_dark_onSurface = Color(0xFFE4E3DB)
val md_theme_dark_surfaceVariant = Color(0xFF45483D)
val md_theme_dark_onSurfaceVariant = Color(0xFFC5C8B9)
val md_theme_dark_outline = Color(0xFF8F9285)
val md_theme_dark_inverseOnSurface = Color(0xFF1B1C18)
val md_theme_dark_inverseSurface = Color(0xFFE4E3DB)
val md_theme_dark_inversePrimary = Color(0xFF466800)
val md_theme_dark_surfaceTint = Color(0xFFABD468)
val md_theme_dark_outlineVariant = Color(0xFF45483D)
val md_theme_dark_scrim = Color(0xFF000000)
